### ISSUE TITLE
add Raccoon

### ISSUE THREAD

**Issue by Gr33ndev** [Gamify-IT/issues#100]
## Requirement
A Racoon has to be in the game

## Current Behavior
No Raccoon is in the Game

## Expected Behavior
A Raccon is in the Game

## DoD
- [x] Raccon is in the Game

**Comment by Gr33ndev** [comment]
maybe inspired by chrome connection lost minigame when unity is loading

**Comment by leonleoff** [comment]
Closed by Gamify-IT/new-tiles@46562ce7a71642119f453a35a32906c456d012b1

**Comment by delvh** [comment]
I really think you should get comfortable with creating PRs.
Don't force me to block pushes to main.
Commits that fix issues should always get a PR.

Also this does not sound closed as this issue was according to my memory intended to be a complete loading game, not just an unused sprite.

**Comment by WuestFlorian** [comment]
Idea: hidden raccoon cave in a dungeon hole

**Comment by Gr33ndev** [comment]
https://github.com/Gamify-IT/overworld/pull/58

**Comment by Gr33ndev** [comment]
<img width="1920" alt="2022-07-27_15h41_27" src="https://user-images.githubusercontent.com/10178466/181261764-624cddaa-3961-4d84-aaeb-8628b8f75b1e.png">

**Comment by delvh** [comment]
german?
