### ISSUE TITLE
make cam following the player

### ISSUE THREAD

**Issue by LeviUniAcc** [Gamify-IT/issues#102]

**Comment by LeviUniAcc** [comment]
i dont like this idea

**Comment by Gr33ndev** [comment]
I like this, nice idea levi

**Comment by LeviUniAcc** [comment]
you play with dirty tricks 😡

**Comment by Gr33ndev** [comment]
![Image](https://user-images.githubusercontent.com/10178466/178952967-9299243c-c821-4705-b1af-7928cb72600e.png)

**Comment by LeviUniAcc** [comment]
![Image](https://user-images.githubusercontent.com/102458061/178953040-d869e626-bfc4-4b09-8080-e348ceb8fa64.png)

**Comment by delvh** [comment]
I still am not quite sure what this issue wants to do, can we close it?

**Comment by delvh** [comment]
Closing due to no response and unclear goal of the issue.
