### ISSUE TITLE
show menu when pressing esc

### ISSUE THREAD

**Issue by Gr33ndev** [Gamify-IT/issues#106]
## Requirement
The menu should be shown

## Current Behavior
The menu is never shown

## Expected Behavior
The menu should be shown

## DoD
- [x] Menu showes up when pressing esc on keyboard
- [x] Menu shows up when pressing esc button in HUD

**Comment by cdingm** [comment]
i believe an extra point should be that the player can not move while in the pause menu, like in other similar games
