### ISSUE TITLE
add Dungeons, NPC & (minigames?) to minimap

### ISSUE THREAD

**Issue by Gr33ndev** [Gamify-IT/issues#108]
## Requirement
Dungeons, NPCs & maybe minigames are showen on the minimap

## Current Behavior
Dungeons, NPCs & maybe minigames are  not showen on the minimap

## Expected Behavior
Dungeons, NPCs & maybe minigames are showen on the minimap

## DoD
- [x] Dungeons are showen on minimap
- [x] NPCs are showen on minimap

**Comment by delvh** [comment]
What about a compromise?
In the minimap, we show only minigames that have been played previously? (Would also relate to #116)

**Comment by Gr33ndev** [comment]
https://github.com/Gamify-IT/overworld/pull/58
