### ISSUE TITLE
Moorhuhn: Minigames results should be saved

### ISSUE THREAD

**Issue by thechinese** [Gamify-IT/issues#121]
## Requirement
Gamify-IT/issues#98

## Expected Behavior
Game results should be persisted in the minigame db and overworld db

## DoD
- [ ] Game results are saved in minigame db
- [ ] Determine which info should be send to the overworld (and how the xp/knowledge is calculated)
- [ ] Results are saved to the overworld

**Comment by delvh** [comment]
Is this issue closed now?
