### ISSUE TITLE
Names for all areas and dungeons

### ISSUE THREAD

**Issue by thechinese** [Gamify-IT/issues#122]
- [x] Names for all areas and dungeons are set

~~- [ ] Names are changed everywhere (docs, code occurences, etc)~~

**Comment by cdingm** [comment]
should the scenes in unity be renamed from World 1 to World 1 Blooming Savanna?

**Comment by delvh** [comment]
Good question. Probably yes as it makes it easier for new developers who are not accustomed to our code base.

**Comment by cdingm** [comment]
if we change the scene names it needs to be done somewhere when no PRs are open or it might create merge errors again
