### ISSUE TITLE
document what to use in java backends for better code quality

### ISSUE THREAD

**Issue by maexled** [Gamify-IT/issues#131]
## Current Behavior

Currently, the java spring-boot backends are written with no formatting, and big mapping from a DTO-Object to Database-Object.

## DoD/ Expected Behavior
- [ ] a code formatting plugin is defined
- [ ] a easy and nice tool for mapping objects in spring was choosen

**Comment by maexled** [comment]
I thought prettier maven plugin would be a nice solution: https://github.com/HubSpot/prettier-maven-plugin

**Comment by delvh** [comment]
Didn't know that plugin yet, nice.
