### ISSUE TITLE
Cleanup Bugfinder

### ISSUE THREAD

**Issue by delvh** [Gamify-IT/issues#135]
For the code review, the Bugfinder should be cleaned up.

## DoD

- [x] Bugfinder is in a presentable state

**Comment by madebyTimo** [comment]
I think after the PR https://github.com/Gamify-IT/bugfinder/pull/19 the bugfinder is in a good presentable state. 

Although I wan't to mention that there are some points that can be improved further. 
- change all bootstrap to bootstrap-vue
- add more tests
