### ISSUE TITLE
fix menu overlay

### ISSUE THREAD

**Issue by Gr33ndev** [Gamify-IT/issues#144]
![Image](https://user-images.githubusercontent.com/10178466/179324033-d527b53b-2c18-4dc7-9001-69cd289274ed.png)

**Comment by delvh** [comment]
a) what exactly do you want to accomplish with this issue?
That all functionality gets translated into English, or also that there is no more placeholder functionality?
b) What was bad enough that you had to delete the original revision of the issue?

**Comment by cdingm** [comment]
> That all functionality gets translated into English
i thought the game should be german? @delvh

**Comment by delvh** [comment]
https://gamifyit-docs.readthedocs.io/en/latest/adr/2022-05-12-program-language.html ?

**Comment by Gr33ndev** [comment]
This issue was about the wrong scaling I opened issue Z for the translation
