### ISSUE TITLE
Integrate Crosswordpuzzle

### ISSUE THREAD

**Issue by Aaron2000119** [Gamify-IT/issues#149]
## Current Behavior
The crosswordpuzzle uses a different method to get the configuration as the moorhuhn game
## Expected Behavior
The crosswordpuzzle uses the same method to get a configuration as the moorhuhn game
## DoD
- [ ] configuration are loaded from the backend while using the same method as the moorhuhn game

**Comment by spethso** [comment]
Chickenshock (here mentioned as moorhuhn game) is a quiz-like game, while Crosswordpuzzle is a different type. Therefore, I close this issue as they require a different configuration.
