### ISSUE TITLE
make all minigame spots animated and fix their colliders

### ISSUE THREAD

**Issue by cdingm** [Gamify-IT/issues#157]
## Requirement
minigame spots are all equal to each other

## Current Behavior
some are animated and some are not, some are blocking the player to walk on them

## Expected Behavior
all are animated and are walkable on

## DoD
~~- [ ] animate all minigame spots in all worlds~~ Extracted to #104
~~- [ ] fix colliders of wrong minigame spots (change layer)~~ Extracted to #104

**Comment by LeviUniAcc** [comment]
this is inside #104, you can cancel this issue i guess
