### ISSUE TITLE
show area name/symbol in minimap to see where you're walking to

### ISSUE THREAD

**Issue by Gr33ndev** [Gamify-IT/issues#161]
## Requirement
The area name/symbol should bein the minimap

## Current Behavior
The area name/symbol is not in the minimap

## Expected Behavior
The area name/symbol is in the minimap

## DoD
- [ ] The area name/symbol is in the minimap

**Comment by delvh** [comment]
? Didn't I see that in your stream already?

**Comment by Gr33ndev** [comment]
no you have only seen the name of the current area under the minimap
