### ISSUE TITLE
Add licenses

### ISSUE THREAD

**Issue by madebyTimo** [Gamify-IT/issues#186]
## Current Behavior

We don't have a license for our services.
The supervisors would like a license, Sandros preference is MIT.

## Expected Behavior / DoD

- [x] We have chosen a suitable license
- [x] The chosen license does not violate licenses of used packages
- [x] All services received this license

**Comment by Gr33ndev** [comment]
**Regex-Game:**
_Dependencies:_
Vue: MIT
VueX: MIT

_Dev-Dependencies:_
@types/jest: MIT
@typescript-eslint/eslint-plugin: MIT
@typescript-eslint/parser: BSD-2-Clause
@vue/cli-plugin-eslint: MIT
@vue/cli-plugin-typescript: MIT
@vue/cli-plugin-unit-jest: MIT
@vue/cli-plugin-vuex: MIT
@vue/cli-service: MIT
@vue/eslint-config-typescript: MIT
@vue/test-utils: MIT
@vue/vue3-jest: MIT
babel-jest: MIT
eslint: MIT
eslint-config-prettier: MIT
eslint-plugin-prettier: MIT
eslint-plugin-vue: MIT
jest: MIT
jest-sonar-reporter: MIT
jsdom: MIT
prettier: MIT
ts-jest: MIT
typescript: Apache-2.0
vite: MIT
vitest: MIT

**Comment by Gr33ndev** [comment]
**Login-Frontend:**
_Dependencies:_
@popperjs/core: MIT
axios: MIT
bootstrap: MIT
bootstrap-vue-3: MIT
vue: MIT
vue-router: MIT
vue-toastification: MIT
vuex: MIT

_Dev-Dependencies:_
@types/jest: MIT
@typescript-eslint/eslint-plugin: MIT
@typescript-eslint/parser: BSD-2-Clause
@vue/cli-plugin-eslint: MIT
@vue/cli-plugin-router: MIT
@vue/cli-plugin-typescript: MIT
@vue/cli-plugin-unit-jest: MIT
@vue/cli-plugin-vuex: MIT
@vue/cli-service: MIT
@vue/eslint-config-typescript: MIT
@vue/test-utils: MIT
@vue/vue3-jest: MIT
babel-jest: MIT
eslint: MIT
eslint-config-prettier: MIT
eslint-plugin-prettier: MIT
eslint-plugin-vue: MIT
jest: MIT
jest-mock-axios: MIT
jest-sonar-reporter: MIT
prettier: MIT
ts-jest: MIT
typescript: Apache-2.0

**Comment by Gr33ndev** [comment]
**Bugfinder:**
_Dependencies:_
bootstrap: MIT
bootstrap-vue-3: MIT
vue: MIT
vue3-highlightjs: ISC
Vuex: MIT

_Dev-Dependencies:_
@types/bootstrap: MIT
@types/jest: MIT
@typescript-eslint/eslint-plugin: MIT
@typescript-eslint/parser: BSD-2-Clause
@vue/cli-plugin-eslint: MIT
@vue/cli-plugin-typescript: MIT
@vue/cli-plugin-unit-jest: MIT
@vue/cli-plugin-vuex: MIT
@vue/cli-service: MIT
@vue/eslint-config-typescript: MIT
@vue/test-utils: MIT
@vue/vue3-jest: MIT
babel-jest: MIT
eslint: MIT
eslint-config-prettier: MIT
eslint-plugin-prettier: MIT
eslint-plugin-vue: MIT
jest: MIT
jest-sonar-reporter: MIT
prettier: MIT
sass: MIT
sass-loader: MIT
ts-jest: MIT
typescript: Apache-2.0
vue-eslint-parser: MIT

**Comment by Gr33ndev** [comment]
**crosswordpuzzle**
_Dependencies:_
axios: MIT
bootstrap: MIT
vue: MIT
vue-router: MIT
vuex: MIT

_Dev-Dependencies:_
@types/bootstrap: MIT
@types/jest: MIT
@typescript-eslint/eslint-plugin: MIT
@typescript-eslint/parser: BSD-2-Clause
@vue/cli-plugin-eslint: MIT
@vue/cli-plugin-router: MIT
@vue/cli-plugin-typescript: MIT
@vue/cli-plugin-unit-jest: MIT
@vue/cli-plugin-vuex: MIT
@vue/cli-service: MIT
@vue/eslint-config-typescript: MIT
@vue/test-utils: MIT
@vue/vue3-jest: MIT
babel-jest: MIT
eslint: MIT
eslint-config-prettier: MIT
eslint-plugin-prettier: MIT
eslint-plugin-vue: MIT
jest: MIT
jest-sonar-reporter: MIT
prettier: MIT
ts-jest: MIT
typescript: Apache-2.0

**Comment by Gr33ndev** [comment]
**git-card-game**
_Dependencies:_
@primer/octicons: MIT
core-js: MIT
vue: MIT


_Dev-Dependencies:_
@babel/core: MIT
@babel/eslint-parser: MIT
@babel/eslint-plugin: MIT
@babel/preset-react: MIT
@types/jest: MIT
@typescript-eslint/eslint-plugin: MIT
@vue/cli-plugin-babel: MIT
@vue/cli-plugin-eslint: MIT
@vue/cli-plugin-typescript: MIT
@vue/cli-plugin-unit-jest: MIT
@vue/cli-service: MIT
@vue/test-utils: MIT
@vue/vue3-jest: MIT
babel-jest: MIT
eslint: MIT
eslint-plugin-flow: BSB-3-Clause
eslint-plugin-flowtype: BSB-3-Clause
eslint-plugin-import: MIT
eslint-plugin-vue: MIT
jest: MIT
jest-sonar-reporter: MIT
ts-jest: MIT
typescript: Apache-2.0

**Comment by Gr33ndev** [comment]
**lecturer-interface**
_Dependencies:_
@popperjs/core: MIT
bootstrap: MIT
bootstrap-vue-3: MIT
vue: MIT
vue-router: MIT
vue-sidebar-menu: MIT
vue-toastification: MIT
vuex: MIT

_Dev-Dependencies:_
@types/jest: MIT
@typescript-eslint/eslint-plugin: MIT
@typescript-eslint/parser: BSD-2-Clause
@vue/cli-plugin-eslint: MIT
@vue/cli-plugin-router: MIT
@vue/cli-plugin-typescript: MIT
@vue/cli-plugin-unit-jest: MIT
@vue/cli-plugin-vuex: MIT
@vue/cli-service: MIT
@vue/eslint-config-typescript: MIT
@vue/test-utils: MIT
@vue/vue3-jest: MIT
babel-jest: MIT
eslint: MIT
eslint-config-prettier: MIT
eslint-plugin-prettier: MIT
eslint-plugin-vue: MIT
jest: MIT
jest-sonar-reporter: MIT
prettier: MIT
ts-jest: MIT
typescript: Apache-2.0

**Comment by Gr33ndev** [comment]
**overworld-backend**
_Dependencies:_
spring-boot-starter-web: Apache-2.0
springdoc-openapi-ui: Apache-2.0
lombok: MIT
mapstruct: Apache-2.0
postgresql: BSD-2-Clause
spring-boot-starter-test: Apache-2.0
spring-boot-starter-data-jpa: Apache-2.0

_Plugins:_
spring-boot-maven-plugin: Apache-2.0
jacoco-maven-plugin: EPL-2.0
maven-jar-plugin: Apache-2.0
prettier-maven-plugin: Apache-2.0
maven-compiler-plugin: Apache-2.0

**Comment by Gr33ndev** [comment]
**moorhuhn-backend**
_Dependencies:_
spring-boot-starter-web: Apache-2.0
lombok: MIT
mapstruct: Apache-2.0
postgresql: BSD-2-Clause
spring-boot-starter-test: Apache-2.0
spring-boot-starter-data-jpa: Apache-2.0
java-jwt: MIT

_Plugins:_
jacoco-maven-plugin: EPL-2.0
maven-jar-plugin: Apache-2.0
prettier-maven-plugin: Apache-2.0
maven-compiler-plugin: Apache-2.0

**Comment by Gr33ndev** [comment]
**crosswordpuzzle-backend**
_Dependencies:_
spring-boot-starter-web: Apache-2.0
lombok: MIT
springdoc-openapi-ui: Apache-2.0
mapstruct: Apache-2.0
postgresql: BSD-2-Clause
spring-boot-starter-test: Apache-2.0
spring-boot-starter-data-jpa: Apache-2.0

_Plugins:_
spring-boot-maven-plugin: Apache-2.0
jacoco-maven-plugin: EPL-2.0
prettier-maven-plugin: Apache-2.0
maven-jar-plugin: Apache-2.0
maven-compiler-plugin: Apache-2.0

**Comment by delvh** [comment]
If I see that correctly: The js/ ts packages won't be the problem, the main thing we need to ensure is that the unity license is compatible with MIT.
Also: How did you manage to list all licenses?
That looks autogenerated...

**Comment by Gr33ndev** [comment]
**login-backend**
_Required:_
github.com/go-openapi/errors: Apache-2.0
github.com/go-openapi/loads: Apache-2.0
github.com/go-openapi/runtime: Apache-2.0
github.com/go-openapi/spec: Apache-2.0
github.com/go-openapi/strfmt: Apache-2.0
github.com/go-openapi/swag: Apache-2.0
github.com/go-openapi/validate: Apache-2.0
github.com/go-swagger/go-swagger: Apache-2.0
github.com/golang-jwt/jwt: MIT
github.com/iancoleman/strcase: MIT
github.com/jessevdk/go-flags: BSD-3-Clause
github.com/joho/godotenv: MIT
github.com/prisma/prisma-client-go: Apache-2.0
github.com/rs/cors: MIT
github.com/shopspring/decimal: MIT
github.com/takuoki/gocase: MIT
golang.org/x/crypto: BSD-3-Clause
golang.org/x/net: BSD-3-Clause

_Indirect Required:_
github.com/asaskevich/govalidator: MIT
github.com/docker/go-units: Apache-2.0
github.com/felixge/httpsnoop: MIT
github.com/fsnotify/fsnotify: BSD-3-Clause
github.com/go-openapi/analysis: Apache-2.0
github.com/go-openapi/inflect: MIT
github.com/go-openapi/jsonpointer: Apache-2.0
github.com/go-openapi/jsonreference: Apache-2.0
github.com/go-stack/stack: MIT
github.com/google/go-cmp: BSD-3-Clause
github.com/google/uuid: BSD-3-Clause
github.com/gorilla/handlers: BSD-2-Clause
github.com/hashicorp/hcl: MPL-2.0
github.com/josharian/intern: MIT
github.com/kr/pretty: MIT
github.com/kr/text: MIT
github.com/magiconair/properties: BSD-2-Clause
github.com/mailru/easyjson: MIT
github.com/mitchellh/mapstructure: MIT
github.com/oklog/ulid: Apache-2.0
github.com/pelletier/go-toml: MIT
github.com/pkg/errors: BSD-2-Clause
github.com/rogpeppe/go-internal: BSD-3-Clause
github.com/spf13/afero: Apache-2.0
github.com/spf13/cast: MIT
github.com/spf13/jwalterweatherman: MIT
github.com/spf13/pflag: BSD-3-Clause
github.com/spf13/viper: MIT
github.com/subosito/gotenv: MIT
github.com/toqueteos/webbrowser: MIT
go.mongodb.org/mongo-driver: Apache-2.0
golang.org/x/mod: BSD-3-Clause
golang.org/x/sys: BSD-3-Clause
golang.org/x/text: BSD-3-Clause
golang.org/x/tools: BSD-3-Clause
golang.org/x/xerrors: BSD-3-Clause
gopkg.in/ini.v1: Apache-2.0
gopkg.in/yaml.v2: Apache-2.0

**Comment by Gr33ndev** [comment]
**Unity:**
https://unity3d.com/de/legal/terms-of-service

**Unity Asset Store:**
https://unity3d.com/de/legal/as_terms

**Comment by Gr33ndev** [comment]
@delvh I will check again but I also think that the main problem will be the unity licenses.
Unfortunately my report is actually created by hand and not generated.

**Comment by Gr33ndev** [comment]
Unless I missed any (please correct me if I did), apart from the Unity licenses, we only use the following licenses: **Apache-2.0**, **BSD-2-Clause**, **BSD-3-Clause**, **EPL-2.0**, **ISC**, **MIT**, **MPL-2.0**

**Comment by delvh** [comment]
Yes, I assumed something like that already.
And those licenses are all compatible with MIT as far as I know.

**Comment by Gr33ndev** [comment]
**Please check this at least one more time**

Apache-2.0 is compatible with MIT
BSD-2-Clause is compatible with MIT
BSD-3-Clause is compatible with MIT
EPL-2.0 is ? with MIT _(I'm not sure if compatibility is important, since only the jacoco-maven-plugin is licensed under the EPL-2.0)_
ISC is compatible with MIT
MIT is compatible with MIT
MPL-2.0 is compatible with MIT

The Unity License is ? with MIT
The Unity Asset Store License is ? with MIT

**Comment by delvh** [comment]
That is my state of knowledge as well.

**Comment by cdingm** [comment]
Zelda Like Tileset: CC0 1.0 - Public Domain Dedication --> No Copyright

**Comment by delvh** [comment]
Sandro has now passed on the question to the legal department, we'll hopefully receive an answer in a few weeks...
