### ISSUE TITLE
Docs: Document repo architectures

### ISSUE THREAD

**Issue by madebyTimo** [Gamify-IT/issues#187]
## Description

We refactored some repos for the code review.
We did not create a file detailing what to look at, what **not** to look  at, if that code is tested, the general code structure...

## DoD

- [x] Such a file was created
- [x] The supervisors received the file
- [x] The file has been uploaded to the documentation
- [x] The review hints have been added for the Overworld
- [x] The review hints have been added for the Overworld Backend
- [x] The review hints have been added for the Moorhuhn
- [x] The review hints have been added for the Moorhuhn Backend
- [x] The review hints have been added for the Bugfinder
- [x] The review hints have been added for the Lecturer Interface
- [x] The review hints have been added for the Finitequiz
- [x] The review hints have been added for the Finitequiz Backend

**Comment by delvh** [comment]
The following assignees have been selected for each service: 

- [ ] @Gr33ndev, @WuestFlorian Overworld
- [ ] @Aaron2000119 Overworld Backend
- [ ] @LeviUniAcc Chickenshock Backend
- [ ] @maexled Bugfinder
- [ ] @Aaron2000119 Lecturer Interface

Filling the templates is now highly prioritized.

**Comment by delvh** [comment]
Files should be under `dev-manuals/architecture` in the docs.
