### ISSUE TITLE
Requirements Engineering

### ISSUE THREAD

**Issue by thechinese** [Gamify-IT/issues#19]
## Current Behavior:
There is no exact document specifying the exact requirements 
The QA should make that the customer receives the right product. 

## DoD:
- [x] List all measure and process that ensure high software quality

**Comment by a91896** [comment]
> ## Current Behavior:
> There is no exact document specifying the exact requirements 
> The QA should make that the customer receives the right product. 
> 
> ## Expected Behavior:
> 
> 
> ## DoD:
> - [ ] List all measure and process that ensure high software quality
> 
> ## Story Points: 
> 

Nice one..1
