### ISSUE TITLE
chickenshock refactor for more qa

### ISSUE THREAD

**Issue by LeviUniAcc** [Gamify-IT/issues#192]
## Current Behavior
1 right answer 4 wrong answers static.
every round is a new scene

## Expected Behavior
dynamic count of wrong answers.
one game scene that gets leaded one time for each game

## DoD
- [x] dynamic count of wrong answers.
- [x] Array with wrong questions and OneToMany mapping.
- [x] game runns in one game scene

**Comment by delvh** [comment]
`13`?
Are you kidding?
This sounds like `2-3`...

**Comment by LeviUniAcc** [comment]
no this is basically completly new frontend

**Comment by LeviUniAcc** [comment]
13 -> 8 because i thought the testplans are part of this but they are not
