### ISSUE TITLE
add Keycloak

### ISSUE THREAD

**Issue by Gr33ndev** [Gamify-IT/issues#193]
## Requirement
We should use Keycloak

## Current Behavior
Login-front & backend is used

## Expected Behavior
Keycloak is used

## DoD
- [x] A database dump for development with Keycloak exists (<https://github.com/Gamify-IT/test-data>)
- [x] We have a working login page with Keycloak for local development (<https://github.com/Gamify-IT/landing-page>)
- [x] It is documented how services can access the user ID and username (update the existing docs)

**Comment by robojones** [comment]
More info in: #194

**Comment by madebyTimo** [comment]
keycloak itself works as expected. This can be tested in the [landing-page](https://github.com/Gamify-IT/landing-page).
When we release the other services it will be added to our run-config.
