### ISSUE TITLE
Familiarize with keycloak

### ISSUE THREAD

**Issue by Gr33ndev** [Gamify-IT/issues#194]
## Requirement
We know keycloak well enough to replace the login with it

## Current Behavior
We are not familiar with keycloak at all

## Expected Behavior
We know keycloak well enough to replace the login with it

## DoD
- [ ] we know keycloak well enough to replace the login with it

**Comment by delvh** [comment]
What's the difference to #193?

**Comment by Gr33ndev** [comment]
Install Keycloak in docker container: https://www.keycloak.org/server/containers
Keycloak with Spring: https://www.baeldung.com/spring-boot-keycloak
Customize Keycloak login: https://www.baeldung.com/keycloak-custom-login-page
Add registration to Keycloak: https://www.baeldung.com/keycloak-user-registration 
Manage access rights with Keycloak: https://www.adesso.de/de/news/blog/verwaltung-von-zugriffsrechten-mit-keycloak-als-iam-system.jsp
Secure REST api with Keycloak: https://medium.com/@bcarunmail/securing-rest-api-using-keycloak-and-spring-oauth2-6ddf3a1efcc2
