### ISSUE TITLE
Create a simple way to load dummy data into the backends

### ISSUE THREAD

**Issue by robojones** [Gamify-IT/issues#195]
## Description

Create a way to load dummy data into the backends. We need this to make our tests reproducible and to speed up development.

This should require **at most** one command or click.

## DoD
- [ ] There exists a way to load dummy data into the backends

**Comment by robojones** [comment]
We could add a bash script with curl requests to initialize the backends. This can be executed automatically, as part of our docker-compose files.

**Comment by delvh** [comment]
Only problem would be if we would require authorization to be sent as well.
Because in this case, this problem will become funny to solve.

**Comment by madebyTimo** [comment]
If cookie authentication is needed we will create a cookie jar and use it

**Comment by delvh** [comment]
What about `curl -K`/ `curl --config`?
