### ISSUE TITLE
Test Plan

### ISSUE THREAD

**Issue by thechinese** [Gamify-IT/issues#20]
## Current Behavior:
There is no documented way to organize tests

## Expected Behavior:
There should be a place where the test strategies of the respective services are documented.

See: https://github.com/IT-REX-Platform/Wiki/wiki/Development--Quality-Assurance-and-Methods--Testing

## DoD:
- [x] Collect all use cases that can occur (TODO: specify what level of detail is required)
- [x] For of those cases, create test strategies and test cases that 

## Story Points:
TODO:

**Comment by Gr33ndev** [comment]
https://github.com/Gamify-IT/docs/pull/49
