### ISSUE TITLE
Design Interface for Professors

### ISSUE THREAD

**Issue by thechinese** [Gamify-IT/issues#21]
### Current Behavior:
Currently we have no interface to create chapters aka. levels in and to assign minigames to it.

### Expected Behavior:
Create a design for the interface.
It should include :
- how the ui looks like
- How to implement it : data format

2 project members should do this task

### DoD:
- [x] A design (sketch) for the interface is created and accepted by a supervisor.
- [x] Uwe approves the design (Feeback)

### Story Points:
3

**Comment by maexled** [comment]
https://github.com/Gamify-IT/docs/blob/main/protocols/prof-interface/2022-06-14-protocol.md

**Comment by maexled** [comment]
# How to handle the data?
## Endpoint of the overworld
The overworld needs an endpoint that can be configured if an area/dungeon can be accessed or not. 
The overworld also needs an endpoint, where are tasks listed, where minigames can be implemented. Therefore it should be possible that you can link the game type and game configuration id (more about it in the next paragraph) to the task, so when the overworld wants to call the game it can the right microservice with the configuration id.

## Endpoint for each minigame
Each minigame should be configurable for each task a lecturer wants to specify (On different minigames, a lecturer wants different questions). Therefore the minigames need different configurations for different tasks. The best idea will be, that every minigame backend offers a configuration endpoint.
It could look like the following:
```
POST configurations/
Body:
{
    id: String,
    configration: OwnConfigurationModel
}
Returns created configuration

GET configurations/
Returns list of configurations

UPDATE configrations/<id>/
Body:
{
    id: String,
    configration: OwnConfigurationModel
}
Returns updated configuration

GET configurations/<id>/
Returns configuration

*The id should be oriented to area/dungeon:
e.g. Area 2, Dungeon 3, Minigame 2: a2-d3-2
```
Later when the overworld calls a microservice game with a configuration id, the minigame can catch the configuration by the id from the database.
