### ISSUE TITLE
add unlocking logic to overworld

### ISSUE THREAD

**Issue by delvh** [Gamify-IT/issues#225]
## DoD
- [ ] all dungeons and world are locked by default
- [ ] its possible to unlock dungeons by completing all minigames with a high enough score
- [ ] its possible to unlock worlds by completing all minigames with a high enough score
- [ ] A testplan for when what is unlocked has been added

**Comment by maexled** [comment]
https://github.com/Gamify-IT/docs/blob/main/dev-manuals/services/overworld/database-model-and-type.md#experience-system

**Comment by delvh** [comment]
https://gamifyit-docs.readthedocs.io/en/latest/dev-manuals/services/overworld/database-model-and-type.html#experience-system
