### ISSUE TITLE
Implement chickenshock backend to overworld backend communication

### ISSUE THREAD

**Issue by delvh** [Gamify-IT/issues#228]
## Requirement
The chickenshock backend needs to communicate with the overworld backend to send result data.

## Current Behavior
The chickenshick backend cannot communicate with the overworld backend.

## Expected Behavior
The chickenshock backend can communicate with the overworld backend.

## DoD
- [x] The chickenshock backend can communicate with the overworld backend. 
- [x] The chickenshock backend sends the result data needed to the overworld backend.

**Comment by LeviUniAcc** [comment]
was implemented inside: Research backend-to-backend communication[#224](https://github.com/Gamify-IT/issues/issues/224)
can be closed.

**Comment by delvh** [comment]
No, the commit hasn't been merged yet.
Please open a PR and merge it first.
