### ISSUE TITLE
Chickenshock: Dynamic time

### ISSUE THREAD

**Issue by LeviUniAcc** [Gamify-IT/issues#239]
## Current Behavior

The gametime is static.

## Expected Behavior

Thie gametime can be set in the lecturer interface or is a default value.

## DoD
- [ ] game time is as long as the lecturer defines it

**Comment by delvh** [comment]
What is missing for this issue?
The configurability in the lecturer interface?

**Comment by marlau97** [comment]
We just added that, waiting for a PR review
