### ISSUE TITLE
Overworld: Add HUD

### ISSUE THREAD

**Issue by delvh** [Gamify-IT/issues#24]
### Current Behavior
Currently, the user is not shown any information about his player in the overworld.

### Expected Behavior
Add a basic HUD for things like the player level, life points, the menu, or the currently carried items.

### DoD:
- [x] The user is shown applicable information about the player

**Comment by cdingm** [comment]
- player level = knowledge level
- maybe minimap
- collectible count
- current area
- achievements overview

**Comment by cdingm** [comment]
concept design

![Image](https://user-images.githubusercontent.com/101562444/175269757-2cbde979-d74e-4b54-8f7d-9a031ae1b078.png)


![Image](https://user-images.githubusercontent.com/101562444/175270066-615c568f-7c84-459d-8e9d-20be9b01cb57.png)

**Comment by delvh** [comment]
Do we want to offer a minimap?
I think that is a question of its own that at least for the next two months I'd answer with no.
This is definitely not on the top of our priority list.
