### ISSUE TITLE
create and fill third party license notice website

### ISSUE THREAD

**Issue by Gr33ndev** [Gamify-IT/issues#245]
Follow up issue of Gamify-IT/issues#240

## Current Behavior

We don't have a third party license notice website

## Expected Behavior

We have a third party license notice website

## DoD
- [x] A Website (in style of: https://www.volkswagen.de/de/mehr/rechtliches/lizenzhinweise-dritter.html) exists on which we display all used third party licenses notices
- [ ] The Website is up-to-date

**Comment by delvh** [comment]
Just noticed there is a separate issue, so here as well:

But this time perhaps do it automated?
https://blog.bitsrc.io/how-i-analyzed-all-npm-dependency-licenses-in-one-go-18de0f7244bc
As far as I know, a similar plugin should exist for maven, so the only unclear thing remains Unity where we can probably simply include the two licenses for Unity and the Unity asset license.

**Comment by Gr33ndev** [comment]
TODO: clarify what was used in chickenshock

**Comment by delvh** [comment]
Unity License and Unity Asset License?

**Comment by Gr33ndev** [comment]
Unity Asset License depends on what the author declares as his license but the default TOS of the Unity Asset store has no need of providing a notice....

**Comment by Gr33ndev** [comment]
Unity itselfe whats to be noticed on the FOSS site... https://unity.com/legal/licenses/unity-companion-license "5. Notices & Third-Party Rights. This License, including the copyright notice associated with the Work, must be provided in all substantial portions of the Work and derivative works thereof (or, if that is impracticable, in any other location where such notices are customarily placed). Further, if the Work is accompanied by a Unity “third-party notices” or similar file, you acknowledge and agree that software or content identified in that file is governed by those separate license terms."
