### ISSUE TITLE
Overworld: Create demo to show how barriers can block off later content

### ISSUE THREAD

**Issue by delvh** [Gamify-IT/issues#25]
### Current Behavior
Currently, we have no temporary barriers between areas to block off yet inaccessible content.

### Expected Behavior
We need to know how to create some kind of barrier so that players can't access later areas until unlocked.

### DoD
- [ ] A demo exists on how to block off paths

**Comment by LeviUniAcc** [comment]
i think this issue is doubled with an issue @marlau97 already made. it contained the destruction of a bush. if so, this issue is useless and can be put to outdated.

**Comment by delvh** [comment]
Only one difference: his bush had no collision.
If the same mechanism can be applied to objects with collision, then this issue can indeed be cancelled.

**Comment by delvh** [comment]
As confirmed by @marlau97:
the current mechanism can be extended arbitrarily if you enlarge the hitbox of the intended object, hence this demo is no longer needed as it is already implemented basically.
