### ISSUE TITLE
Global: handle CourseId and PlayerId

### ISSUE THREAD

**Issue by madebyTimo** [Gamify-IT/issues#251]
## Description

The Overworld should show the course selected in the course-selection
If it is there first time in the course, a player statistic has to be created in this course for the player

## DoD
- [x] when the player has no player statistic in the course, a new player statistic has to be created for the course
- [x] CourseId is set dynamically (passed in path) 
- [x] Player username is set dynamically in the overworld (passed in local storage)
- [x] PlayerId is available in local storage and used by the overworld
~~- [ ] PlayerStatistic is created with UserId from access token in Cookie (overworld-backend)~~
- [x] PlayerId is set dynamically in chickenshock (passed in cookie)
- [x] PlayerId is set dynamically in finitequiz (passed in cookie)
~- [ ] PlayerId is set dynamically in crosswordpuzzle (passed in cookie)~
~- [ ] PlayerId is set dynamically in bugfinder (passed in cookie)~

**Comment by LeviUniAcc** [comment]
removed crosswordpuzzle/ bugfinder couse they are not even finished yet.
