### ISSUE TITLE
Bugfinder: Continue working on bugfinder backend

### ISSUE THREAD

**Issue by IlijazM** [Gamify-IT/issues#261]
## Description

The bugfinder currently has a backend. There are missing tests, documentation, code refactoring

## DoD
~~- [ ] backend implemented~~
~~- [ ] frontend is adjusted to use the backend~~
~~- [ ] frontend test plans are adapted~~

## Previous Issue

#229

**Comment by delvh** [comment]
Not finished at sprint end.
