### ISSUE TITLE
Dynamically set playerId and courseId

### ISSUE THREAD

**Issue by WuestFlorian** [Gamify-IT/issues#263]
## Current Behavior
PlayerId and courseId are set statically in the overworld and minigames.

## Expected Behavior
PlayerId and course Id are set dynamically.

## DoD
- [ ] CourseId is set dynamically (passed in path) 
- [ ] PlayerId is set dynamically in the overworld (passed in cookie)
- [ ] PlayerId is set dynamically in chickenshock (passed in cookie)
- [ ] PlayerId is set dynamically in finitequiz (passed in cookie)
- [ ] PlayerId is set dynamically in crosswordpuzzle (passed in cookie)
- [ ] PlayerId is set dynamically in bugfinder (passed in cookie)

**Comment by delvh** [comment]
Duplicate of #251
