### ISSUE TITLE
Finitequiz + Chickenshock + Overworld: Change how minigames get called

### ISSUE THREAD

**Issue by Aaron2000119** [Gamify-IT/issues#268]
## Current Behavior

Currently the minigames get called like this /api/minigames/$MINIGAME#$ID.

## Expected Behavior

The minigames should called like this /api/minigames/$MINIGAME/$ID/.

## DoD
- [x] The minigames get called like this: /api/minigames/$MINIGAME/$ID/
- [x] The chickenshock accepts the id
- [x] The finite quiz accetps the id

**Comment by LeviUniAcc** [comment]
crosswordpuzzle did also work without any changes💎
