### ISSUE TITLE
Global: Adapt docker-compose files to use Keycloak

### ISSUE THREAD

**Issue by madebyTimo** [Gamify-IT/issues#274]
- [x] Keycloak is used instead of login-frontend & -backend in all applicable development docker-compose files
- [x] Keycloak is used instead of login-frontend & -backend in our staging and production deployment

**Comment by madebyTimo** [comment]
- [ ] chickenshock
- [ ] chickenshock backend
- [ ] overworld
- [ ] overworld backend
- [ ] landing page
- [ ] crosswordpuzzle
- [ ] crosswordpuzzle backend
- [ ] bugfinder
- [ ] bugfinder backend
- [ ] finitequiz
- [ ] finitequiz backend

**Comment by cdingm** [comment]
what about the lecturer interface docker compose files?

**Comment by delvh** [comment]
Should we perhaps exclude bugfinder and bugfinder backend for now, so that we can still close it in this sprint?

**Comment by madebyTimo** [comment]
I currentlz add it to the actual development branch of Ilijaz
