### ISSUE TITLE
Chickenshock: Fix HUD sizing

### ISSUE THREAD

**Issue by marlau97** [Gamify-IT/issues#283]
## Current Behavior

Some HUD elements are not visible at some screen sizes

## Expected Behavior

HUD size fits screen no matter how you resize it

## DoD
- [ ] HUD size fits screen no matter how you resize it

**Comment by LeviUniAcc** [comment]
big unity problems with courser

**Comment by LeviUniAcc** [comment]
accidently pushed on main sry bros
