### ISSUE TITLE
Bugfinder: Continue working on bugfinder backend

### ISSUE THREAD

**Issue by IlijazM** [Gamify-IT/issues#295]
## Description

The bugfinder currently has a backend. There are missing tests, documentation, code refactoring

## DoD
- [x] backend implemented
- [x] frontend is adjusted to use the backend
- [x] frontend test plans are adapted
- [x] code is documented
- [x] code is tested

## Previous Issue

#261

**Comment by delvh** [comment]
When you include reviews, this issue is at least a `5`…

**Comment by delvh** [comment]
Well, according to the DoD, everything is finished…
