### ISSUE TITLE
Lecturer Interface: edit hash for the new maps once they are merged in docs

### ISSUE THREAD

**Issue by cdingm** [Gamify-IT/issues#336]
after https://github.com/Gamify-IT/docs/pull/161 is merged get hash and add to config file

**Comment by maexled** [comment]
Please also update the mapCommitHash in the lecturer interface [config file](https://github.com/Gamify-IT/lecturer-interface/blob/main/src/config.ts)

**Comment by cdingm** [comment]
> Please also update the mapCommitHash in the lecturer interface [config file](https://github.com/Gamify-IT/lecturer-interface/blob/main/src/config.ts)

isnt this exactly what you have to do to see the new maps in the lecturer interface?

**Comment by delvh** [comment]
Yep, you both want exactly the same thing.
I don't even know why this deserved its own issue, but okay…
