### ISSUE TITLE
Landing page: fix routing

### ISSUE THREAD

**Issue by robojones** [Gamify-IT/issues#337]
The routing on the landing page does not work as expected. The user is often redirected to `/app` instead of `/start`. When not logged in, the user is not redirected to the login, when visiting page `/start`

# DoD
- [ ] when not logged in, the user should be redirected to the login page
- [ ] after the login, the user is redirected to the game selection

**Comment by madebyTimo** [comment]
Why the DoD is not ticked? The PR fulfills the DoD

**Comment by delvh** [comment]
The question is still valid.
