### ISSUE TITLE
Legal: update third-party-licenses

### ISSUE THREAD

**Issue by delvh** [Gamify-IT/issues#354]

**Comment by Gr33ndev** [comment]
protobuf 4.21.2 => 4.21.6

node_modules/@vue/vue-loader-v15/node_modules/loader-utils 1.4.0 => 1.4.2
node_modules/loader-utils 2.0.2 => 2.0.4
node_modules/vue-style-loader/node_modules/loader-utils 1.4.0 => 1.4.2
loader-utils 1.4.0 => 1.4.2
loader-utils 2.0.2 => 2.0.4
loader-utils 1.4.0 => 1.4.2

node_modules/babel-loader/node_modules/loader-utils 2.0.2 => 2.0.4
node_modules/loader-utils 1.4.0 => 1.4.2
node_modules/thread-loader/node_modules/loader-utils 2.0.2 => 2.0.4
node_modules/vue-loader/node_modules/loader-utils 2.0.2 => 2.0.4
loader-utils 2.0.2 => 2.0.4
loader-utils 1.4.0 => 1.4.2
loader-utils 2.0.2 => 2.0.4
loader-utils 2.0.2 => 2.0.4
