### ISSUE TITLE
towercrush: understand nginx problems

### ISSUE THREAD

**Issue by delvh** [Gamify-IT/issues#356]
## Current Behavior

Everything works as expected but nginx redirect is not as usual

## Expected Behavior

Redirect works just like the other minigames

## DoD
- [x] understand nginx redirect 
- [x] fix nginx redirect

**Comment by LeviUniAcc** [comment]
should work now, but timo will add another deployment that upadtes towercrush on every development branch push to test the multiplayer game without merging everytime into main (for development). @madebyTimo

**Comment by madebyTimo** [comment]
This will be done in #372
