### ISSUE TITLE
towercrush: join function

### ISSUE THREAD

**Issue by LeviUniAcc** [Gamify-IT/issues#375]
## Current Behavior

currently the connection is experimental and bad

## Expected Behavior

refactor the connection like we (martin, jonathan, levi) discussed, (no double names, no wrong filtering, no open lobbies after all left)

## DoD
- [x] fixed joining game
- [x] tested with multiple players

**Comment by delvh** [comment]
> refactor the connection like we (martin, jonathan, levi) discussed

Please elaborate.
