### ISSUE TITLE
Towercrush: refactor lobby status synchronization

### ISSUE THREAD

**Issue by robojones** [Gamify-IT/issues#382]
## Current Behavior

When a user joins or leaves a lobby, a join/leave message is sent to all other members of the lobby. All members maintain their own local lists of members.

## Expected Behavior

The server should add or remove members and send the complete status of the lobby to all members. This status includes the complete list of members (and later on the teams and other data).

## DoD
- [x] Replace `JoinTeamMeesage` with a new `UpdateLobbyMessage` containing the complete state of the lobby as stored on the server.
- [x] Test changes on test deployment

**Comment by delvh** [comment]
Closed by https://github.com/Gamify-IT/towercrush-backend/pull/6
