### ISSUE TITLE
Sketch Overworld Design

### ISSUE THREAD

**Issue by delvh** [Gamify-IT/issues#39]
### Precondition
#14 

### Current Behavior:
Currently we encounter the problem that we don't have a sketch of the overworld design

### Expected Behavior:
Create a sketch which contains the five different areas and overall overworld design structures, such as connections between areas.

## Original Issue
https://github.com/Gamify-IT/docs/issues/24

### DoD:
- [ ]  A sketch exists which is accepted by Uwe.
- [ ]  A rough sketch is enough, see recording 
- [ ] The sketch is review by the overworld team

**Comment by cdingm** [comment]
is this still needed after our discussion with uwe today?
