### ISSUE TITLE
Add DevOps files for memory mingame

### ISSUE THREAD

**Issue by maexled** [Gamify-IT/issues#480]
## Current Behavior

The memory and memory-backend repositories are not released as docker images. Also multiple docker compose files are missing. The memory backend is also not integrated in lecturer interface docker compose files and on the run config. 

## Expected Behavior

The memory and memory-backend repositories will be pushed as docker images with github actions. Needed docker compose files are created and updated in the memory repositories as well as in lecturer interface and run config repository.

## DoD
- [x] memory repository has all needed github action workflows
- [x] memory repository has all needed docker compose files and the Dockerfile
- [x] memory-backend repository has all needed github action workflows
- [x] memory-backend repository has all needed docker compose files and the Dockerfile
- [x] memory is integrated into the lecturer interface docker compose files
- [x] memory is integrated into the run config

**Comment by madebyTimo** [comment]
Is the test-data for the memory-backend also part of this issue?
