### ISSUE TITLE
Build Dungeon 1

### ISSUE THREAD

**Issue by madebyTimo** [Gamify-IT/issues#50]
### Current Behavior:
Currently we have no dungeon 1.

### Expected Behavior:
Create dungeon 1.

### DoD:

- [x]  Dungeon 1 is drawn in Unity.
- [x]  Dungeon 1 is explore-able.
- [x]  Dungeon 1 has 12 places for minigames.

**Comment by Gr33ndev** [comment]
<img width="830" alt="2022-07-05_16h41_04" src="https://user-images.githubusercontent.com/10178466/177354242-fda79da3-a0c5-4483-a1c1-f2de0e99876c.png">
