### ISSUE TITLE
Overworld: "Area not unlocked" - close button does not work correctly

### ISSUE THREAD

**Issue by Gr33ndev** [Gamify-IT/issues#503]
**Needs investigation if it is still present**

## Description

The <kbd>close</kbd> Button of the `This area is not unlocked yet` dialogue does not feel like a normal button.
Reports about it include
- the hitbox is not correct
- the cursor is not changed to a button cursor when hovering
- clicking is sometimes not accepted
- dialogue can only be closed by reloading the page completely

## DoD

- [x] <kbd>close</kbd> Button is a real button
- [ ] cursor is changed when hovering over it
- [x] its hitbox is its entire visibility
- [x] there is no chance of clicking the button not working

**Comment by delvh** [comment]
@Gr33ndev is fairly certain that this has been fixed.

**Comment by Gr33ndev** [comment]
is working
