### ISSUE TITLE
implement CIs

### ISSUE THREAD

**Issue by madebyTimo** [Gamify-IT/issues#53]
## Current Behavior
Currently, we have some working CIs, but the CIs for unity projects are only partial and need pre-builds.

## Expected Behavior
All CIs build the whole project from scratch and release them as docker image.

## DoD
- [x] all CI build from scratch, especially unity
- [x] automatic release of docker images
- [x] CIs are working without errors

**Comment by Gr33ndev** [comment]
https://github.com/Gamify-IT/moorhuhn/pull/20
