### ISSUE TITLE
Github Actions runner permission fails at multiple runs

### ISSUE THREAD

**Issue by madebyTimo** [Gamify-IT/issues#60]
## Current Behavior
After one run the CI fails in the next run because it can't remove files created by the last run. [exapmle failure](https://github.com/Gamify-IT/moorhuhn/runs/7010590808)
The actual solution is to run a cleanup task at the end of every run like you can see [here](https://github.com/Gamify-IT/moorhuhn/blob/1b9ca2749ef793b0510e88b54b77779081c06173/.github/workflows/deploy-docker-image-on-release.yml)

## Expected Behavior
Runs don't fail because they already run once and the folder isn't deleted manually (or by a cleanup task).

## DoD

If there is a solution:
- [x] runs don't fail because they already run once
- [x] CI-caching works
- [x] no actual CI fails cause of the described error

If there is no solution:
- [ ] related [Github Action Issues](https://github.com/actions/runner/issues) are checked and documented
- [ ] cleanup task is added to all actual CIs
- [ ] need of cleanup task is announced to project members
- [ ] no actual CI fails cause of the described error

**Comment by madebyTimo** [comment]
Also problems at [login backend](/home/githubrunner/actions-runner/_work/_actions/github/codeql-action)

**Comment by madebyTimo** [comment]
It is a general problem with Github-Actions. Related issues can be found amount many other issues [here](https://github.com/actions/runner/issues/434) and [there](https://github.com/actions/checkout/issues/211).

As workaround we decided to run the runner as root, so it has all permission. This shouldn't be a problem because jobs are only triggered by team-members and the runner runs on a dedicated VM.

**Comment by delvh** [comment]
While I am typically not in favor of running programs as root, I can at least understand it in this case.
Should we inform Professor Becker about this?

**Comment by madebyTimo** [comment]
I don't think we need to do this. It's a dedicated VM only for the runner and the old user also had docker rights which lead to nearly same permissions as root permission
